### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by cfoellmann** [Fmstrat/samba-domain#38]
# 1.0
- [ ] upgrade base image to `ubuntu:focal` __vs:__ #34 / #31 
- [ ] split image (#37)
  - [ ] latest
  - [ ] latest-multisite
- [ ] add `ntpd` service (#8 + https://github.com/Fmstrat/samba-domain/tree/ntpd)
- [ ] improve DNS
  - [ ] ntpd might help: https://github.com/Fmstrat/samba-domain/issues/30#issuecomment-729129128

# 2.0
- [ ] provide additional image based on `alpine` (latest-alpine)

# Dev Env
- [ ] Create a "Project"/Milestone here on github.
- [ ] Setup CI via Travis CI (or equivalent) to test changes to the image

**Comment by tpimh** [comment]
Any plans on having a tag based on Alpine?

**Comment by cfoellmann** [comment]
@tpimh would be nice but the ubuntu image should work 100% before switching the base

**Comment by cfoellmann** [comment]
@tpimh I just looked at the alpine packages and samba is a lot closer to newest source version in the alpine apk than ubuntu focal.
Might be a little bit more cutting edge for better or worse

**Comment by cfoellmann** [comment]
@Fmstrat I am tempted to test all ongoing changes on alpine since it would reduce the image footprint dramatically. Maybe in an `alpine` branch

**Comment by cfoellmann** [comment]
I was looking more intensively at the fork from @burnbabyburn and it is looking very impressive what has changed/improved there!

I think @burnbabyburn is a good candidate as a co-maintainer for this project!!

please let us get this thing up to a good state soon. I want to deploy these images next month a few times 😉

**Comment by tpimh** [comment]
@cfoellmann I'm totally willing to test the Alpine image!

**Comment by burnbabyburn** [comment]
have a look here for an alpine based one
https://github.com/instantlinux/docker-tools/tree/main/images/samba-dc
